[WIP] Add Organization entity
NadezhdaGlin/Web-Transportation pull request #7
Opened 2022-09-28 15:07 UTC by NadezhdaGlin

2022-10-04 10:54 UTC, grigorymarsavin commented on app/models/user.rb
> +  def operator?
с точки зрения нейминга/конвенций такие методы лучше называть 
`is_operator?`

2022-10-04 10:54 UTC, grigorymarsavin commented on app/models/user.rb
> +    role == 'organization admin'
плохая идея использовать тут пробел, роль лучше прописать через нижнее подчеркивание - oranisation_admin

2022-10-04 10:54 UTC, grigorymarsavin commented on app/policies/cargo_policy.rb
> +  class Scope
один файл - один класс 
CargoPolicy олжен выглядеть так: 

```ruby
  attr_reader :current_user, :record

  def initialize(current_user, record)
    @current_user = current_user
    @record = record
  end
 
```

и дальше методы на проверку политики (индекс, create и так далее)

2022-10-04 10:54 UTC, grigorymarsavin commented on spec/factories/organizations.rb
> +    name { "MyString" }
если верить файлу db/migrate/20220928125506_create_organizations.rb
то эта колонка должна называться name_org, не name

2022-10-10 15:27 UTC, grigorymarsavin requested changes

2022-10-10 15:27 UTC, grigorymarsavin commented on app/controllers/cargos_controller.rb
> +      @cargos = @cargos.where(user_id: params[:operator_id_filter]) if params[:operator_id_filter].present?
Ты объявляешь @cargos на 7 строке, затем тут переобъявляешь его же
Лучше сделать if/else конструкцию и @cargos удет объявлено один единственный раз

if current_user.org_admin? 
   @users = ...
   @cargos = Cargo.where(user_id: params[:operator_id_filter]) if params[:operator_id_filter].present?
 elseif current_user.is_just_oeprator? 
     @cargo = Cargo.where(user_id: current_user.id) 
  end
  
  и authorize @cargos должно быть в конце экшена, насколько я помню по примерам

2022-10-10 15:27 UTC, grigorymarsavin commented on app/controllers/cargos_controller.rb
> +    # binding.pry
рубокоп не детектит это как ошибку?

2022-10-10 15:39 UTC, NadezhdaGlin commented on app/controllers/cargos_controller.rb
> +    # binding.pry
нет

2022-10-12 07:36 UTC, merged